### ISSUE TITLE
Lets make master a protected branch

### ISSUE THREAD

**Issue by mithuns** [CodeForSocialGood/calltocode.org#163]
I am seeing last few commits merged in master had failed CI build. 
I am not sure if master is a protected branch or not, but would request the project owner to mark master as a protected branch so no one would be able to directly push to master branch.

**Comment by timdavish** [comment]
> I am seeing last few commits merged in master had failed CI build.

The last few commits merged into `master` have failed due to a travis bug that's causing dependencies to be unable to be downloaded. Our build is fine, and this can be checked locally by running `yarn test && yarn e2e`

> I am not sure if master is a protected branch or not

The `master` branch is already protected (this can be viewed [here](https://github.com/CodeForSocialGood/calltocode.org/branches), shown by the 'lock' symbol next to the branch name). AFAIK, @bbmoz is the only one with the power to push directly to the `master` branch and he only does so when he wants to flaunt his power (just kidding lol).

The concern is much appreciated 👍

**Comment by mithuns** [comment]
I am new here, just was not sure.

**Comment by timdavish** [comment]
@mithuns welcome! you should come say hi in the [Slack channel](http://join-our-slack.code4socialgood.org/) 😄

**Comment by mithuns** [comment]
I was waiting for Joe to send me an invite.
